// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​o​a​r​d​z
	 */
	title: string
	/**
	 * A​d​v​e​n​t​u​r​e​ ​A​w​a​i​t​s​ ​-​ ​P​l​a​n​,​ ​D​o​c​u​m​e​n​t​,​ ​a​n​d​ ​S​h​a​r​e​ ​Y​o​u​r​ ​T​h​r​i​l​l​s​.
	 */
	tagline: string
	/**
	 * S​i​g​n​ ​u​p​ ​w​i​t​h
	 */
	signUp: string
}

export type TranslationFunctions = {
	/**
	 * Boardz
	 */
	title: () => LocalizedString
	/**
	 * Adventure Awaits - Plan, Document, and Share Your Thrills.
	 */
	tagline: () => LocalizedString
	/**
	 * Sign up with
	 */
	signUp: () => LocalizedString
}

export type Formatters = {}
